version: '3.7'

services:
  keycloakdb:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloakdb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      DB_SCHEMA: public
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_HTTP_PORT: 8080
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, 
      # and it shouldn't be used in production without knowledge. It is highly recommended that you read the 
      # PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 5000:8080
    depends_on:
      - keycloakdb

  driversoderingmanagement-db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - '1436:1433'
    environment:
      - DB_USER=SA
      - SA_PASSWORD=#localDockerPassword#
      - DB_CONTAINER_NAME=dev_ordering_management
      - ACCEPT_EULA=Y
    volumes:
      - cargoorderingservice-data:/var/lib/sqlserver/data

  driversblogmanagement-db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - '1435:1433'
    environment:
      - DB_USER=SA
      - SA_PASSWORD=#localDockerPassword#
      - DB_CONTAINER_NAME=dev_blog_management
      - ACCEPT_EULA=Y
    volumes:
      - driversblogmanagement-data:/var/lib/sqlserver/data

  driversmanagement-db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - '1434:1433'
    environment:
      - DB_USER=SA
      - SA_PASSWORD=#localDockerPassword#
      - DB_CONTAINER_NAME=dev_drivers_management
      - ACCEPT_EULA=Y
    volumes:
      - driversmanagement-data:/var/lib/sqlserver/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    # port mappings: https://www.jaegertracing.io/docs/1.32/getting-started/
    ports:
      - "58681:5775/udp"
      - "58680:6831/udp"
      - "58682:6832/udp"
      - "58683:5778"
      - "58684:16686"
      - "58685:14250"
      - "58686:14268"
      - "58687:14269"
      - "58688:9411"
        
volumes:
  # compose volumes marker - do not delete
  keycloak-data:
  cargoorderingservice-data:
  driversblogmanagement-data:
  driversmanagement-data:
